[env:FrameWorkBadge]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_upload.flash_size = 4MB
board_upload.maximum_size = 4194304
framework = arduino

board_build.core = earlephilhower
board_build.filesystem = littlefs
board_build.filesystem_size = 1048576
board_build.partitions = partitions.csv

lib_deps =
  arminjo/IRremote@^4.4.0
  FastLED
  adafruit/Adafruit GFX Library
  https://github.com/marcmerlin/FastLED_NeoMatrix.git
  bblanchon/ArduinoJson@^7.0.0

monitor_speed = 115200
