M48
; DRILL file {KiCad 8.0.5} date 2025-08-16T16:19:24-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-08-16T16:19:24-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X6.3805Y-5.2689
X6.3805Y-5.4964
T2
X6.5689Y-5.2953
X8.7341Y-5.4094
M30
